name: Build and deploy to dev
on:
  push:
    branches:
      - '**'

jobs:
  build-push:
    if: github.actor != 'dependabot[bot]'
    name: Build and push
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'
      - uses: gradle/actions/setup-gradle@v5

      - name: Build
        run: ./gradlew clean build

      - name: Push docker image to GAR
        uses: nais/docker-build-push@v0
        id: docker-build-push
        env:
          ACTIONS_RUNTIME_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          team: tsm
          image_suffix: dev
    outputs:
      image: "${{ steps.docker-build-push.outputs.image }}"

  deploy-prod:
    if: github.actor != 'dependabot[bot]' && github.ref_name == 'main'
    name: Deploy to prod
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    needs: [build-push]
    steps:
      - uses: actions/checkout@v5
      - name: Deploy to NAIS
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: .nais/nais-prod.yaml
          VAR: image=${{ needs.build-push.outputs.image }}

  deploy-dev:
    if: github.actor != 'dependabot[bot]'
    name: Deploy to dev
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    needs: [build-push]
    steps:
      - uses: actions/checkout@v5
      - name: Deploy to NAIS
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: .nais/nais-dev.yaml
          VAR: image=${{ needs.build-push.outputs.image }}
